apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: anchor-php-backend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/project: acp-vertex-core
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/acp-vertex-core/anchor-php:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: DB_CONNECTION_TYPE
          value: unix-socket
